// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpai96vlEUNjwaMObQizDPhTDcsYvXLWQ',
    appId: '1:812478130857:web:86cc05dbec7872a6a6d7b8',
    messagingSenderId: '812478130857',
    projectId: 'movie-verse-43367',
    authDomain: 'movie-verse-43367.firebaseapp.com',
    storageBucket: 'movie-verse-43367.firebasestorage.app',
    measurementId: 'G-S85396YBMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTUD3TDM-w7R2yBu0F-TYF5PZlmYv3bwo',
    appId: '1:812478130857:android:83066944bc34344da6d7b8',
    messagingSenderId: '812478130857',
    projectId: 'movie-verse-43367',
    storageBucket: 'movie-verse-43367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnGuFzTPixfnwgqFwmvEFe1O4tg8Bu2tU',
    appId: '1:812478130857:ios:d4f080405812117ca6d7b8',
    messagingSenderId: '812478130857',
    projectId: 'movie-verse-43367',
    storageBucket: 'movie-verse-43367.firebasestorage.app',
    iosBundleId: 'com.example.movieVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnGuFzTPixfnwgqFwmvEFe1O4tg8Bu2tU',
    appId: '1:812478130857:ios:d4f080405812117ca6d7b8',
    messagingSenderId: '812478130857',
    projectId: 'movie-verse-43367',
    storageBucket: 'movie-verse-43367.firebasestorage.app',
    iosBundleId: 'com.example.movieVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpai96vlEUNjwaMObQizDPhTDcsYvXLWQ',
    appId: '1:812478130857:web:61e555dd8cf74bd6a6d7b8',
    messagingSenderId: '812478130857',
    projectId: 'movie-verse-43367',
    authDomain: 'movie-verse-43367.firebaseapp.com',
    storageBucket: 'movie-verse-43367.firebasestorage.app',
    measurementId: 'G-L3L58063D7',
  );
}
